# Generated by Django 2.1.5 on 2020-07-03 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(blank=True, default='', max_length=30, verbose_name='领导')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=30, null=True, verbose_name='QQ')),
                ('user_photo', models.ImageField(blank=True, default='user-photo/user_photo_demo.jpg', upload_to='user-photo/%Y/%m', verbose_name='头像')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_first', models.BooleanField(default=True, verbose_name='是否第一次登陆')),
                ('to_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户属性',
                'verbose_name_plural': '用户属性',
            },
        ),
    ]
