# Generated by Django 2.1.5 on 2020-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='remark',
            field=models.TextField(default='', verbose_name='备注信息'),
        ),
    ]
