# Generated by Django 2.2.2 on 2020-01-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '打分项目',
                'verbose_name_plural': '打分项目',
            },
        ),
        migrations.CreateModel(
            name='ScoreUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(blank=True, default=0, verbose_name='排序')),
                ('to_score_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_center.ScoreProject', verbose_name='关联打分项目')),
                ('to_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.UserProfile', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '参与打分的人员表',
                'verbose_name_plural': '参与打分的人员表',
                'unique_together': {('to_score_project', 'to_user_profile')},
            },
        ),
        migrations.CreateModel(
            name='ScoreOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('score_min', models.IntegerField(verbose_name='最小分值')),
                ('score_max', models.IntegerField(verbose_name='最大分值')),
                ('to_score_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_center.ScoreProject', verbose_name='关联打分项目')),
            ],
            options={
                'verbose_name': '打分项目',
                'verbose_name_plural': '打分项目',
            },
        ),
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('score_result', models.FloatField(blank=True, default=0, verbose_name='分值')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.UserProfile', verbose_name='打分人员')),
                ('to_score_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_center.ScoreOption', verbose_name='关联打分项')),
                ('to_score_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_center.ScoreUserProfile', verbose_name='关联打分人员表')),
            ],
            options={
                'verbose_name': '打分结果',
                'verbose_name_plural': ('打分结果',),
                'unique_together': {('to_score_user_profile', 'to_score_option', 'create_user')},
            },
        ),
    ]
