# Generated by Django 2.1.1 on 2020-01-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_userprofile_leader'),
        ('score_center', '0002_userprofilescoreproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilescoreproject',
            name='exclude_user_profile',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='exclude_user_profile', to='user_center.UserProfile', verbose_name='不评选人员'),
        ),
    ]
